#!/bin/bash

rts_ps_check(){
	comm_ps="rtdsrvcomm rtdsrvprices rtdsrvord rtdsrvtrades rtdsrvctr rtdsrvlimits rtdsrvaom rtdcalcindex"
	tango_ps="tango tangosrvmon tangotradabledb"
	sfe_ps="rtdsfeif"

	echo "checking RTS COMM Processes"
	for ps in $comm_ps
	do
		if [ -z `pidof $ps` ]
		then
			echo "$ps			NOT RUNNING"
		else
			echo "$ps			RUNNING"
		fi
	done

	
	echo "checking RTS TANGO Processes"
	for ps in $tango_ps
	do
		if [ -z `pidof $ps` ]
		then
			echo "$ps			NOT RUNNING"
		else
			echo "$ps			RUNNING"
		fi
	done

	
	echo "checking RTS SFE Interface Processes"
	for ps in $sfe_ps
	do
		if [ -z `pidof $ps` ]
		then
			echo "$ps			NOT RUNNING"
		else
			echo "$ps			RUNNING"
		fi
	done
}


echo "Stopping SFE interface"
/opt/rts/rtd/scripts/rtd_stop_rtdsfeif
echo "Stopping ELB Server if any(Tango Trader Web Client Download)"
unset rtdenv ; /opt/rts/rtd/scripts/rts_elbsrv stop
echo "Stopping INET Server if exists"
/opt/rts/rtd/scripts/rtd_stop_inetsrv
echo "Stopping Tango"
/opt/rts/tango/scripts/tango_stop &

tango_lock=/opt/rts/tango/tmp/start/tango/tango.lck
echo "waiting for tango to stop"
sleep 5
while [ -f $tango_lock ]
do
	echo "force shutting down tango server"	
	/opt/rts/tango/scripts/tangoserver_stop -k
done
sleep 5

echo "Stopping Comm server"
/opt/rts/rtd/scripts/rtd_stop_server

sleep 2
rts_ps_check

echo "Starting Comm server"
/opt/rts/rtd/scripts/rtd_start_server
echo "Starting Tango"
/opt/rts/tango/scripts/tango_start
echo "Staring INET Server if possible"
/opt/rts/rtd/scripts/rtd_start_inetsrv
echo "Starting ELB Server"
unset rtdenv ; export JAVA_HOME=/opt/rts/jre1.6.0_27 ; /opt/rts/rtd/scripts/rts_elbsrv start
echo "Starting SFE interface"
/opt/rts/rtd/scripts/rtd_start_rtdsfeif
echo "Enabling Process Shielding"
/opt/rts/rtd/scripts/shield.pl 

rts_ps_check


